# Generated by Django 4.2.6 on 2023-10-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Contraseña',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Id_rol',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Nr_doc',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Nombre',
            field=models.CharField(max_length=38, null=True),
        ),
    ]
