# Generated by Django 4.2.6 on 2023-10-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_usuarios_contraseña_usuarios_id_rol_usuarios_nr_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Nr_doc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
